title: Kenneth Brandt
description: GCP+GxP quality systems and quality operations,inspection readiness,vendor oversight,and practical execution.
url: "https://kennethjbrandt.com"
baseurl: ""
lang: en-US

theme: minima

social:
  name: Kenneth Brandt
  links:
    - https://www.linkedin.com/in/kennethjbrandt/
    
header_pages:
  - blog.md
  - about.md
  - now.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
author: Kenneth Brandt

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
