title: Kenneth Brandt
description: Director, GCP & GxP Quality Systems â€¢ Biotech & Biologics
url: "https://kennethjbrandt.com"
baseurl: ""

theme: minima

minima:
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/kennethjbrandt/" }
    - { platform: github,   user_url: "https://github.com/kjbrandt2" }
header_pages:
  - blog.md
  - about.md
  - now.md
